In [10]:
import numpy as np
ar=np.array([0,1,2,3]) # 리스트를 넣으면 넘파이의 배열을 만들어주는 함수
ar
ar2=np.array([0,1,2.5]) # 데이터 타입이 다름(int와 float), 그렇지만 정수가 -> 실수로 자동 형변환되어 error가 나지 않음
ar2
ar3=np.array([0,'a',1]) # 숫자와 문자가 섞여있음 -> 모두 문자형으로 자동 형 변환
ar3
ar4=np.array([0,'a',1,True,3.14]) # 정수, 불린, 실수, 문자 -> 다 문자 타입으로 바뀐다(하나만 다르더라도)
ar4
ar5=np.array([0,1,True,3.14]) # 정수, 불린, 실수 -> 모두 실수로 자동 형 변환
ar5
ar6=np.array([0,1,True]) # 정수, 불린 -> 모두 정수로 자동 형 변환
ar6

array([0, 1, 1])

In [11]:
type(ar)
# n차원 데이터를 array로 만들어 작업

numpy.ndarray

In [15]:
# 백터화 연산 : 배열(array)의 각 요소에 대한 반복 연산을 하나의 명령어로 빠르게 처리(1차원 데이터)

data=list(range(0,10))
# [파이썬 모드] 데이터 배열의 값을 모두 2배한 다음 answer에 저장한 후 출력
answer=[]
for d in data:
    answer.append(d*2) # 10번 문장을 수행
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [17]:
# [넘파이 모드] 2배 연산
x=np.array(data)
x
x*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# 그럼 리스트는 안되나?

In [21]:
print(data*2) #  데이터에 리스트를 2번 출력해라([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("="*50)
print(x*2) # x배열의 각 요소값을 2배해라([ 0  2  4  6  8 10 12 14 16 18])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [31]:
# [넘파이 연산]

a=np.array([1,2,3])
b=np.array([10,20,30])
2*a+b # 요소 간 연산이 이루어짐!
a==2 # 각각의 요소에 2가 있는지 1:1로 대응 ---->1=2, 2=2, 3=2 비교
b>10
(a==2) & (b>10) # &로 묶여져 있어서 양쪽의 결과가 모두 참일때만 True(True & True=True,제외하고는 모두 False)

array([False,  True, False])

In [29]:
# [리스트 연산]

a2=[1,2,3]
b2=[4,5,6]
a2*2+b2 # 결합이 되어버림, 리스트에서는 *가 반복,ㅡ +가 이어서(붙여서) 연결
a2==2 # a2는 2가 아니고, [1,2,3]이다---> [1,2,3]=2 비교

False

In [36]:
# [배열을 이용한 행렬 구조]

# 0차원 array(배열) : 스칼라
# 1차원 array(배열) : 백터
# 2차원 array(배열) : 행렬

c=np.array([[0,1,2],[3,4,5]]) #2차원 배열(행렬)
# -> 안쪽 리스트의 갯수(열), 바깥쪽 리스트의 갯수(행) -> 2*3배열
print(c)
len(c) # 행의 개수
c[0] # 첫번째 행 출력([0, 1, 2])
len(c[0]) # 첫번째 행 길이

[[0 1 2]
 [3 4 5]]


3

In [39]:
# [기본적인 리스트 표현방법]

d=np.array(list(range(1,25)))
d
d.reshape(6,4) # 행 6개, 열 4개로 출력

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [40]:
d=d.reshape(2,3,4) # 2는 면, 3은 행, 4는 열 => 3차원 구조
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [41]:
# 3차원 배열의 행, 열, 깊이(2,3,4)

len(d) # 가장 바깥쪽에 있는 대괄호, 행의 개수

2

In [42]:
len(d[0]) # 열의 개수

3

In [43]:
len(d[0][0]) # 깊이

4

In [46]:
a=np.array([1,2,3])
print(a.ndim) # 1차원, dim : 차원
a.shape # shape : 배열의 크기

1


(3,)

In [47]:
c=np.array([[0,1,2],[3,4,5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [50]:
d.ndim # 3차원이라 3
d.shape

(2, 3, 4)

In [52]:
a=np.array([0,1,2,3,4])
a[2] # 2번 인덱스
a[-1] # 마지막 1번째 인덱스

4

In [57]:
# 다차원일 때, 행 열 지정
c=np.array([[0,1,2],[3,4,5]]) 
c[0,1]
c[1,2]
c[-1] # 마지막 행을 의미
c[-1,-1] # 마지막 행의 마지막 열, c[1,2]와 같음

5

In [59]:
# 두 번째 열 2,4를 추출하고 싶을 때
c[:,1]
c[1,1:] # 두번째 행의 두번째 열부터 마지막 열까지

array([4, 5])

In [62]:
c[:1,] # 0번 인덱스 행만 추출. [0,1,2]
c[:1,:1] # 0번 인덱스 행, 0번 인덱스 열 추출
c[:1,:2] # 0번 인덱스 행, 0 ~ 2-1열 번 인덱스 열 추출

array([[0, 1]])

In [63]:
# 파이썬 불린 추출과 같이, 넘파이에서도 불린 추출 가능

In [69]:
a=np.array([0,1,2,3])
idx=np.array([True,False,True,False])
a[idx] # True에 해당하는 값만 추출, 데이터 갯수가 맞아야 함(길이가 맞아야!)
# -> index error가 발생할 수 있으므로 주의!

a%2 # 각각의 요소값을 2로 나눈 나머지
a%2==0 # 불린으로 출력([ True, False,  True, False])
a[a%2==0] # True에 해당하는 값만 추출 ([0, 2])

array([0, 2])

In [70]:
a=np.array([10,20,30,40,50])
idx=np.array([0,2,4])
a[idx]

array([10, 30, 50])

In [72]:
# [문제]

# m=np.array([[0,1,2,3,4],
#            [5,6,7,8,9],
#            [10,11,12,13,14]])
# 이 행렬에서 값 7을 인덱싱한다
# 이 행렬에서 값 14을 인덱싱한다
# 이 행렬에서 배열 [6,7]을 슬라이싱한다
# 이 행렬에서 배열 [7,12]을 슬라이싱한다
# 이 행렬에서 배열 [[3,4],[8,9]]을 슬라이싱한다

In [83]:
m=np.array([[0,1,2,3,4],
           [5,6,7,8,9],
           [10,11,12,13,14]])

m[0]

array([0, 1, 2, 3, 4])

In [99]:
m[1][2]
m[-2][2]
m[-2][-3]

7

In [188]:
m[2][4]
# m[-4][0]

14

In [111]:
a=np.array(list(range(1,13)))
a
a=a.reshape(3,4)

In [112]:
a[:,[True,False,False,True]] # 불린 형태로도 추출 가능하다

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [113]:
a[[True,False,True],:]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [114]:
# 위치를 지정할 때 수치 입력(먼저 추출하고 싶을 때)
a[[2,0,1],:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [115]:
x=np.array([1,2,3])
x.dtype # dtype : 데이터 타입을 알려주는 속성, 저장되어 있는 타입을 알 수 있다
x=np.array([1,1,2,1,3,1])
x.dtype # x변수에 저장된 데이터의 타압 
type(x) # x변수의 타입(자료구조, numpy, ndarray)

dtype('int32')

In [116]:
# 데이터 타입이 정수 + 실수가 섞여 있다면?
x=np.array([1,2,3.14]) # 실수 형태로 출력
x.dtype

dtype('float64')

In [120]:
# 데이터 타입 직접 지정해주기
x=np.array([1,2,3],dtype="float")
x.dtype
x

# dtype을 명시하지 않으면 넘파이에서 내부적으로 추정하여 데이터 타입 지정 
# dtype을 명시하면 명시된 타입으로 변환되어 저장

array([1., 2., 3.])

In [121]:
# 요소간의 덧셈
x[0]+x[1]

3.0

In [122]:
# infinite_number : 무한대를 나타내는 상수, 무한대 표현 가능

x=np.array([0,1,-1,0])
y=np.array([1,0,0,0])
x/y

# array([  0.,  inf(양의 무한대), -inf(음의 무한대,  nan])
# inf : 무한대, NaN : 정의할 수 없는 숫자(Not a Number)

C:\Users\B-8\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """
C:\Users\B-8\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """


array([  0.,  inf, -inf,  nan])

In [123]:
np.log(0)

C:\Users\B-8\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [124]:
x=np.zeros(3) # array([0., 0., 0.]) /1차원
x

array([0., 0., 0.])

In [130]:
x=np.zeros((2,3)) # 튜플 형태로 크기를 정의하여 다차원 배열을 만들 수 있다(2,3,4...차원)
x
x.dtype
# 기본적으로 float으로 저장됨

dtype('float64')

In [131]:
# x=np.zeros((2,3),dtype="int") 
x=np.zeros((2,3),dtype="i")  # int를 축약해서 사용할 수 있음
x
# x.dtype

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [132]:
y=np.zeros_like(x) # x와 같은 구조(2행 3열)로 만들되 0으로 초기화하여 y로 저장
y

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [133]:
x=np.ones((2,3,4)) # 2행 3열 깊이4
x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [135]:
z=np.ones_like(y) # y와 동일한 구조에 값을 1로 채운다
z
# 1로 채우는데 어떤 구조를 가져와서 채울 것인가

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [137]:
# range 파이썬에서 리스트를 만들 때 사용 <=> 넘파이에서는 arange와 같음
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
np.arange(2,11,3) #11은 포함 안함

array([2, 5, 8])

In [141]:
# linspace : 선형 구간 지정
np.linspace(0,100,5) # 선형 구간을 5개로 분할한다는 의미

array([  0.,  25.,  50.,  75., 100.])

In [143]:
a=np.array([[1,2,3],[4,5,6]])
a.T # Transpose : 행과 열을 교환(전치 행렬을 만들 때 사용)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [147]:
a=np.arange(12)
# a=np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]) 예1)
# a=np.array(list(range(0,12)))  예2)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [150]:
a.reshape(3,4)
a.reshape(3,-1) # 행만 3개로 하면 되, 열(-1)은 너가 알아서 계산~

a.reshape(2,2,3)
a.reshape(2,2,-1) # 경우의 수가 많으면 error, 경우의 수가 1개인 경우만 자동으로 계산됨

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [154]:
a=a.reshape(2,-1,2)
a.shape

# 1차원 데이터를 다른 차원으로 변환할 때는 reshape 함수를 쓴다
# flatten : 다른(n) 차원을 1차원으로 변환하는 함수(평평하게 해서 1차원이 된다)
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [155]:
a.ravel()
# revel : 3차원을 1차원으로 만들어주는 함수

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [156]:
x=np.arange(5)
x # 1차원

array([0, 1, 2, 3, 4])

In [163]:
x.reshape(1,5) # 대괄호 개수로 차원 구별, 2개 있으므로 1행 5열의 2차원 행렬
# 주의 : 위의 수식과 결과값은 같으나, 자료형 상이!!!!

x.flatten() # 1차원으로 다시 만들어줘야 동일

array([0, 1, 2, 3, 4])

In [160]:
x=x.reshape(1,5) # 1행 5열
x.shape

(1, 5)

In [162]:
x=x.reshape(5,1) # 5행 1열
x.shape
x

# 위의 수식과 상이하다

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [167]:
x=np.arange(5)
x=x[:,np.newaxis]
x

# newaxis : 배열에 대한 차원을 1만큼 증가시킬 때 사용

x.shape

(5, 1)

In [168]:
# 배열 간 연결 작업
# hstack : 행의 수가 같은 배열을 옆으로 연결(수평방향으로)  ->  열이 증가
x1=np.ones((2,3))
x1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [170]:
x2=np.zeros((2,2))
x2

array([[0., 0.],
       [0., 0.]])

In [177]:
# x1와 x2를 합치고 싶을 때(2행 5열로)
np.hstack([x2,x1]) # x2를 기준으로 우측에 x1이 연결
np.hstack([x1,x2]) # x1를 기준으로 우측에 x2이 연결


x3=np.zeros((3,2))
x3

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [178]:
# np.hstack([x1,x3]) # 크기가 맞기 않기 때문에 에러

In [175]:
# vstack : 위, 아래 배열을 연결(수직방향으로) -> 행이 증가
y1=np.ones((2,3))
y2=np.zeros((3,3))
np.vstack([y1,y2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])