In [4]:
import numpy as np
a1=np.ones((2,3))
a1
a2=np.zeros((2,2)) # 튜를로 채워져서 출력
a2

np.hstack([a1,a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [6]:
b1=np.ones((2,3))
b1
b2=np.zeros((3,3))
b2 # 열의 갯수가 같기 때문에 연결
np.vstack([b1,b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# dstack : 행, 열이 아닌 깊이(depth) 뱡향으로 배열을 합친다. 가장 안쪽의 원소의 차원이 증가
# h와 v stack에 비해 적게 사용된다

c1=np.ones((3,4))
c1
c2=np.zeros((3,4))
c2

#(3,4,2)   ----> 두 면이 포개지듯이 합쳐짐 
k=np.dstack([c1,c2])
k.shape

(3, 4, 2)

In [12]:
# axis : 1이면 두번째 차원으로 새로운 차원이 생김
c=np.stack([c1,c2],axis=1)
c
c.shape # 2개의 (3,4)  -> 1개의 (3,2,4)
# dstack으로 새로운 차원을 삽입하면 마지막 차원으로 삽입되는데, axis를 사용하여 순서 재구성 가능

(3, 2, 4)

백터화 연산

In [18]:
from sklearn.datasets import load_iris
iris=load_iris()
iris

# 0 : 세토사, 2: 버지니카

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [19]:
# 데이터 유형 : 데이터 개수나 형태에 따라 4가지로 분류된다
# 1) 스칼라 : 1개의 숫자로만 이루어진 데이터(보통 x로 표시)
# 2) 백터 : 여러개의 숫자가 특정한 순서대로 모여있는 것(숫자 순서가 매우 중요!)
#    ex) 포도 2개, 사과 5개, 배 3개 => 매출액 2*100+5*200+3*300 = 2100
#        자신과 약속(포도, 사과 배 순으로 기입하기로!) -> (2,5,3), (3,4,2)...
#        1열 백터는 포도, 2열 백터는 사과.. 등으로 열 백터가 만들어진다(행, 열에 따라 행백터, 열백터가 됨)

In [22]:
x=np.arange(1,10001)
y=np.arange(10001,20001)
z=np.zeros_like(x)
for i in range(10000):
    z[i]=x[i]+y[i]  # 이 문장을 10000번 수행하여 더한 결과 => 비효율적...
z 

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [23]:
k=x+y # 백터화 연산 : for문보다 간단하게 출력
k

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [27]:
a=np.array([1,2,3,4])
b=np.array([4,2,3,4])
c=np.array([1,2,3,4])
print(a==b) # 백터화 연산을 통해 각 요소별 비교연산
      
# all : 백터의 모든 연산이 다 같은지 비교하고 싶을 때    
print(np.all(a==b)) # 전체(모든 원소)에 대해 다 같은지 연산
print(np.all(a==c))

[False  True  True  True]
False
True


In [31]:
# exp : 자연상수 얻고 싶을 때

x=np.arange(5)
np.exp(x) # exp 함수 : 자연상수 2.718
# 2.718의 0승 => 1

10**x # 10의 x승에 대한 5개의 결과값 출력

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [39]:
x=np.arange(10)
100*x
# 스칼라 * 백터도 연산 가능(x는 백터 , 100은 스칼라)

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [40]:
x=np.arange(12).reshape(3,4)
100*x # 스칼라 * 행렬 도 백터로 연산이 가능하다

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [38]:
# 기본적으로 연산을 하려면 배열의 크기가 같아야 하나, 넘파이에서는 가능하다
# 브로드캐스팅 : 크기가 서로 다른 두 배열이 연산이 가능하도록 확장시키는 기능

x=np.arange(5)
y=np.ones_like(x)
x+y # 각각의 요소간 덧셈(크기가 같기 때문에 괜춘)

x+1 # 브로드캐스팅(1이 다섯개가 만들어지고 요소간 덧셈이 이루어진 것)


# 늘리는 건 가능하지만, 반대로 줄일 수는 없음!

array([1, 2, 3, 4, 5])

In [49]:
x=np.vstack([range(7)[i:i+3] for i in range(5)])
x
# i : 0~4

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [50]:
y=np.arange(5)[:,np.newaxis] # newaxis : 새로운 차원(축) 추가(2차원으로 저장되어짐)
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [51]:
x+y
# 열의 갯수가 맞지 않아서 오류가 나야하지만, 브로드캐스팅이 이루어져 연산이 가능하다!

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [59]:
x=np.array([51,32,43,74])
# np.sum(x)
x.sum()
x.max()
x.argmin() # argmin : 최소값의 위치를 알려주는 함수(32가 저장되어 있는 1번)
x.argmax() # argmax : 최댓값의 위치
x.mean()
np.median(x)

# 1차원인 x를 sum으로 내리니 0차원이 되버림
# ex) 10행 5열의 행단위 평균을 구하면 => 10개의 수치(1차원 백터)
# 넘파이에서는 차원이 축소되는 함수 많음(sum, min, max...)

np.all([True,True,False]) # 하나라도 False면 False
np.all([True,True,True])
np.any([True,True,False]) # 하나라도 True면 True

True

In [ ]:
# 연산 결과 예측

a=np.array([1,2,3,2])
b=np.array([2,2,3,2])
c=np.array([6,4,4,5])
((a<=b)&(b<=c)).all() # all : 전체가 True일때만 True
# (T,T,T,T)&(T,T,T,T) => (T,T,T,T).all() => True

In [63]:
# 리스트 comprehension
# 데이터를 5행 3열로 만들어주고 싶을 때,

x=[range(7)[i:i+3] for i in range(5)] # 범위를 나타내는 함수가 반드시 있어야!
x=np.vstack([range(7)[i:i+3] for i in range(5)])
x

# 마지막 수의 다음 숫자로 범위 지정

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])